# Generated by Django 3.2.5 on 2022-06-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name': 'Bio-Data', 'verbose_name_plural': 'Bio-Datas'},
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='address',
        ),
        migrations.AddField(
            model_name='biodata',
            name='nationality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
